language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
script: 
  - python tests/repo_test.py
  - cd tests
  - coverage run --source=pailab --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/*,*/ml_repo/remote_gcs.py ./repo_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/*,*/ml_repo/remote_gcs.py ./repo_disk_storage_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/*,*/ml_repo/remote_gcs.py ./SQLiteJobRunner_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/*,*/ml_repo/remote_gcs.py ./repo_git_handler_test.py
  - coverage run --source=pailab -a --omit=*/tools_gc.py,*/analysis/*,*/externals/*,*/tools/*,*/ml_repo/remote_gcs.py ./tutorial_test.py
  - codecov
